var dr_O    = [0, 0, 0, 0];
var dr_L    = [1, 0, 0, 0];
var dr_U    = [0, 1, 0, 0];
var dr_R    = [0, 0, 1, 0];
var dr_D    = [0, 0, 0, 1];
var dr_LURD = [1, 1, 1, 1];
var dr_LUR  = [1, 1, 1, 0];
var dr_LU   = [1, 1, 0, 0];
var dr_LR   = [1, 0, 1, 0];
var dr_LD   = [1, 0, 0, 1];
var dr_LUD  = [1, 1, 0, 1];
var dr_LRD  = [1, 0, 1, 1];
var dr_URD  = [0, 1, 1, 1];
var dr_UR   = [0, 1, 1, 0];
var dr_UD   = [0, 1, 0, 1];
var dr_RD   = [0, 0, 1, 1];

var dungeon_list = new Dungeons([
   new Dungeon('Катакомбы', [
       // 1й этаж
       new Floor(1, [
          new Cell(1, 22, dr_U, 'Коридор', null, ['door']),
          new Cell(1, 21, dr_UD, 'Коридор', null, null),
          new Cell(1, 20, dr_URD, 'Коридор', null, ['drainbottom1']),
          new Cell(1, 19, dr_URD, 'Коридор', null, null),
          new Cell(1, 18, dr_URD, 'Коридор', [{name: 'sm', level:8, count: 1}], ['gobelin01'], null),
          new Cell(1, 17, dr_URD, 'Коридор', null, null),
          new Cell(1, 16, dr_UD, 'Коридор', null, null),
          new Cell(1, 15, dr_D, 'Коридор', [{name: 'sm', level:8, count: 1},{name: 'rm', level:7, count: 2}], null),
          new Cell(1, 14, dr_D, 'Коридор', null, ['brik']),
          new Cell(1, 11, dr_U, 'Коридор', null, ['bed']),
          new Cell(1, 10, dr_R, 'Коридор', null, null),
          new Cell(1,  9, dr_U, 'Коридор', null, ['bed']),
          new Cell(1,  8, dr_R, 'Коридор', null, null),
          new Cell(1,  7, dr_U, 'Коридор', null, ['bed']),
          new Cell(1,  6, dr_R, 'Коридор', null, null),
          new Cell(1,  5, dr_U, 'Коридор', null, ['bed']),
          new Cell(1,  4, dr_R, 'Коридор', null, null),
          new Cell(1,  3, dr_U, 'Коридор', null, ['bed']),
          new Cell(1,  2, dr_R, 'Коридор', null, null),

          new Cell(2, 20, dr_LUR, 'Коридор', null, null),
          new Cell(2, 19, dr_LUD, 'Коридор', null, null),
          new Cell(2, 18, dr_LUD, 'Коридор', [{name: 'sm', level:8, count: 1}], null),
          new Cell(2, 17, dr_LRD, 'Коридор', null, null),
          new Cell(2, 14, dr_R, 'Коридор', null, ['teleportdemshut']),
          new Cell(2, 11, dr_U, 'Коридор', null, ['chest4']),
          new Cell(2, 10, dr_LR, 'Коридор', [{name: 'og', level:8, count: 1}], null),
          new Cell(2,  9, dr_U, 'Коридор', null, ['chest1dem1']),
          new Cell(2,  8, dr_LR, 'Коридор', [{name: 'lit', level:8, count: 1},{name: 'lit', level:7, count: 4}], null),
          new Cell(2,  7, dr_U, 'Коридор', null, ['chest1dem1']),
          new Cell(2,  6, dr_LR, 'Коридор', null, null),
          new Cell(2,  5, dr_U, 'Коридор', null, ['chest1dem1']),
          new Cell(2,  4, dr_LR, 'Коридор', [{name: 'lit', level:8, count: 2}], null),
          new Cell(2,  3, dr_U, 'Коридор', null, ['chest1dem1']),
          new Cell(2,  2, dr_LR, 'Коридор', null, null),

          new Cell(3, 20, dr_LR, 'Коридор', [{name: 'smm', level:8, count: 1}], null),
          new Cell(3, 18, dr_LUR, 'Коридор', null, ['brik']),
          new Cell(3, 17, dr_LUR, 'Коридор', [{name: 'rm', level:7, count: 6}], null),
          new Cell(3, 16, dr_UD, 'Коридор', null, null),
          new Cell(3, 15, dr_UD, 'Коридор', [{name: 'smm', level:8, count: 1},{name: 'rm', level:7, count: 2}], null),
          new Cell(3, 14, dr_D, 'Коридор', null, null),
          new Cell(3, 13, dr_D, 'Коридор', null, ['teleportdemchern']),
          new Cell(3, 10, dr_LR, 'Коридор', null, null),
          new Cell(3,  8, dr_LR, 'Коридор', null, null),
          new Cell(3,  6, dr_LR, 'Коридор', null, null),
          new Cell(3,  4, dr_LR, 'Коридор', null, null),
          new Cell(3,  2, dr_LR, 'Коридор', null, null),

          new Cell(4, 20, dr_LUR, 'Коридор', null, null),
          new Cell(4, 19, dr_UD, 'Коридор', [{name: 'sm', level:8, count: 2}], null),
          new Cell(4, 18, dr_UD, 'Коридор', null, null),
          new Cell(4, 17, dr_LRD, 'Коридор', null, ['drainbottom2']),
          new Cell(4, 14, dr_L, 'Коридор', null, ['teleportdemepisk']),
          new Cell(4, 10, dr_LU, 'Коридор', [{name: 'ng', level:9, count: 2}], null),
          new Cell(4,  9, dr_UD, 'Коридор', null, null),
          new Cell(4,  8, dr_LURD, 'Коридор', null, null),
          new Cell(4,  7, dr_UD, 'Коридор', null, null),
          new Cell(4,  6, dr_LUD, 'Коридор', [{name: 'ng', level:8, count: 2}], null),
          new Cell(4,  5, dr_UD, 'Коридор', null, null),
          new Cell(4,  4, dr_LUD, 'Коридор', null, null),
          new Cell(4,  3, dr_UD, 'Коридор', [{name: 'lit', level:7, count: 6}], null),
          new Cell(4,  2, dr_LD, 'Коридор', null, null),

          new Cell(5, 20, dr_L, 'Коридор', [{name: 'sm', level:8, count: 1},{name: 'rm', level:7, count: 2}], null),
          new Cell(5, 17, dr_LUR, 'Коридор', [{name: 'smm', level:8, count: 1},{name: 'rm', level:7, count: 2}], null),
          new Cell(5, 16, dr_UD, 'Коридор', null, null),
          new Cell(5, 15, dr_UD, 'Коридор', [{name: 'sm', level:8, count: 2},{name: 'smm', level:8, count: 1}], null),
          new Cell(5, 14, dr_UD, 'Коридор', null, null),
          new Cell(5, 13, dr_UD, 'Коридор', null, ['drainbottom3']),
          new Cell(5, 12, dr_D, 'Коридор', [{name: 'smm', level:8, count: 1, alignment:1}], null),
          new Cell(5, 11, dr_D, 'Коридор', null, ['chest3']),
          new Cell(5, 10, dr_LR, 'Коридор', null, ['barrikada']),
          new Cell(5,  8, dr_LR, 'Коридор', null, null),
          new Cell(5,  4, dr_L, 'Коридор', null, ['teleport41']),

          new Cell(6, 20, dr_L, 'Коридор', null, ['brik']),
          new Cell(6, 17, dr_LR, 'Коридор', null, null),
          new Cell(6, 10, dr_UR, 'Коридор', [{name: 'ng', level:8, count: 2},{name: 'lit', level:7, count: 2}], null),
          new Cell(6,  9, dr_UD, 'Коридор', null, null),
          new Cell(6,  8, dr_LURD, 'Коридор', [{name: 'sg', level:8, count: 2}], null),
          new Cell(6,  7, dr_D, 'Коридор', null, null),
          new Cell(6,  6, dr_UD, 'Коридор', null, ['door1']),
          new Cell(6,  5, dr_UD, 'Коридор', [{name: 'ng', level:9, count: 1}], ['key35']),
          new Cell(6,  4, dr_UD, 'Коридор', null, null),
          new Cell(6,  3, dr_UD, 'Коридор', null, null),
          new Cell(6,  2, dr_RD, 'Коридор', [{name: 'rg', level:8, count: 2},{name: 'ng', level:8, count: 1}], null),
          new Cell(6,  1, dr_D, 'Коридор', null, ['drainbottom4']),

          new Cell(7, 20, dr_R, 'Коридор', null, ['brik']),
          new Cell(7, 18, dr_UR, 'Коридор', null, null),
          new Cell(7, 17, dr_LD, 'Коридор', null, null), // запрет идти на ловушку
          new Cell(7, 16, dr_RD, 'Коридор', null, ['skelet1']),
          new Cell(7, 10, dr_LR, 'Коридор', null, null),
          new Cell(7,  8, dr_LR, 'Коридор', null, null),
          new Cell(7,  4, dr_R, 'Коридор', null, ['door2']),
          new Cell(7,  2, dr_LR, 'Коридор', null, null),

          new Cell(8, 21, dr_R, 'Коридор', null, ['proboina']),
          new Cell(8, 20, dr_UR, 'Коридор', null, null),
          new Cell(8, 19, dr_UD, 'Коридор', [{name: 'sm', level:8, count: 1},{name: 'rm', level:7, count: 3}], null),
          new Cell(8, 18, dr_LRD, 'Коридор', null, null),
          new Cell(8, 17, dr_LURD, 'Коридор', null, ['stat1']),
          new Cell(8, 16, dr_UR, 'Коридор', null, null),
          new Cell(8, 15, dr_UD, 'Коридор', [{name: 'sm', level:8, count: 1},{name: 'smm', level:8, count: 2}], null),
          new Cell(8, 14, dr_UD, 'Коридор', null, null),
          new Cell(8, 13, dr_UD, 'Коридор', null, null),
          new Cell(8, 12, dr_UD, 'Коридор', [{name: 'sm', level:9, count: 1},{name: 'sm', level:8, count: 1}], null),
          new Cell(8, 11, dr_UD, 'Коридор', [{name: 'ng', level:8, count: 2},{name: 'sg', level:8, count: 1}], null),
          new Cell(8, 10, dr_LD, 'Коридор', null, null),
          new Cell(8,  9, dr_UR, 'Коридор', [{name: 'sg', level:8, count: 3}], null),
          new Cell(8,  8, dr_LD, 'Коридор', null, null),
          new Cell(8,  7, dr_D, 'Коридор', null, ['draintop']),
          new Cell(8,  5, dr_U, 'Коридор', null, ['chest22']),
          new Cell(8,  4, dr_LR, 'Коридор', null, null),
          new Cell(8,  3, dr_URD, 'Коридор', null, ['danger05']),
          new Cell(8,  2, dr_LR, 'Коридор', null, null),

          new Cell(9, 21, dr_LU, 'Коридор', [{name: 'smm', level:8, count: 1},{name: 'rm', level:8, count: 2}], null),
          new Cell(9, 20, dr_LD, 'Коридор', null, ['drainbottom2']),
          new Cell(9, 18, dr_LU, 'Коридор', null, null),
          new Cell(9, 17, dr_UD, 'Коридор', [{name: 'sm', level:8, count: 2}], null),
          new Cell(9, 16, dr_LD, 'Коридор', null, null),
          new Cell(9,  9, dr_LR, 'Коридор', null, null),
          new Cell(9,  8, dr_LRD, 'Коридор', null, ['liteLiveFountain']),
          new Cell(9,  4, dr_LUR, 'Коридор', null, null),
          new Cell(9,  3, dr_UD, 'Коридор', [{name: 'ng', level:8, count: 2},{name: 'sg', level:8, count: 1},{name: 'lit', level:7, count: 2}], null),
          new Cell(9,  2, dr_LD, 'Коридор', null, null),

          new Cell(10, 21,dr_L, 'Коридор', null, ['brik']),
          new Cell(10, 11,dr_U, 'Коридор', null, ['chest121']),
          new Cell(10, 10,dr_U, 'Коридор', null, null),
          new Cell(10,  9,dr_LUD, 'Коридор', [{name: 'bs', level:9, count: 1}], null),
          new Cell(10,  8,dr_D, 'Коридор', null, null),
          new Cell(10,  7,dr_D, 'Коридор', null, ['chest2']),
          new Cell(10,  4,dr_L, 'Коридор', null, ['chest121']),

          new Cell(13, 19,dr_U, 'Коридор', null, ['probenter']),
          new Cell(13, 18,dr_UD, 'Коридор', [{name: 'rm',level:7,count:7}], null),
          new Cell(13, 17,dr_RD, 'Коридор', null, null),

          new Cell(14, 17,dr_LU, 'Коридор', [{name: 'sl', level:8, count: 2}], null),
          new Cell(14, 16,dr_URD, 'Коридор', [{name: 'sm',level:8,count:2},{name: 'rm',level:7,count:2}], null),
          new Cell(14, 15,dr_UD, 'Коридор', null, null),
          new Cell(14, 14,dr_D, 'Коридор', null, null),
          new Cell(14, 13,dr_D, 'Коридор', null, ['memoryFountain']),

          new Cell(15, 17,dr_LUR, 'Коридор', null, ['garbage']),
          new Cell(15, 16,dr_LR, 'Коридор', null, null),

          new Cell(16, 19,dr_U, 'Коридор', null, ['garbage']),
          new Cell(16, 18,dr_U, 'Коридор', [{name: 'rm',level:8,count:1,alignment: 1}], null),
          new Cell(16, 17,dr_URD, 'Коридор', [{name: 'sl', level:8, count: 2}], null),
          new Cell(16, 16,dr_LUD, 'Коридор', [{name: 'sm',level:8,count:2},{name: 'rm',level:8,count:2}], null),
          new Cell(16, 15,dr_UD, 'Коридор', [{name: 'zsl', level:8, count: 1}], null),
          new Cell(16, 14,dr_UD, 'Коридор', null, null),
          new Cell(16, 13,dr_RD, 'Коридор', null, ['skelet12']),

          new Cell(17, 17,dr_L, 'Коридор', null, null),
          new Cell(17, 16,dr_LD, 'Коридор', null, ['garbage']),
          new Cell(17, 13,dr_LR, 'Коридор', null, null),

          new Cell(18, 13,dr_L, 'Коридор', null, ['proboina2'])
       ]),

       // 2й этаж
       new Floor(2, [
          new Cell(1, 10, dr_U, 'Коридор', null, ['ghostFountain']),
          new Cell(1,  9, dr_U, 'Коридор', [{name: 'sg', level:8, count: 2},{name: 'rg', level:9, count: 2}], null),
          new Cell(1,  8, dr_UD, 'Коридор', null, null),
          new Cell(1,  7, dr_RD, 'Коридор', null, null),
          new Cell(1,  4, dr_UR, 'Коридор', null, null),
          new Cell(1,  3, dr_UD, 'Коридор', [{name: 'ng', level:8, count: 2},{name: 'rg', level:9, count: 1}], null),
          new Cell(1,  2, dr_UD, 'Коридор', null, null),
          new Cell(1,  1, dr_D, 'Коридор', null, ['drainenter']),

          new Cell(2,  7, dr_LUR, 'Коридор', null, null),
          new Cell(2,  6, dr_UD, 'Коридор', [{name: 'stg', level:9, count: 1},{name: 'sg', level:8, count: 2}], null),
          new Cell(2,  5, dr_URD, 'Коридор', null, null),
          new Cell(2,  4, dr_LRD, 'Коридор', null, null),

          new Cell(3, 10, dr_U, 'Коридор', null, ['chestenter']),
          new Cell(3,  9, dr_U, 'Коридор', null, ['danger02']),
          new Cell(3,  8, dr_U, 'Коридор', null, null),
          new Cell(3,  7, dr_LRD, 'Коридор', null, null),
          new Cell(3,  6, dr_LURD, 'Коридор', null, ['altar2']),
          new Cell(3,  5, dr_LU, 'Коридор', null, ['stat3']),
          new Cell(3,  4, dr_LRD, 'Коридор', [{name: 'stg', level:9, count: 1},{name: 'sg', level:9, count: 2}], null),
          new Cell(3,  3, dr_UD, 'Коридор', null, ['dangerdem3']),
          new Cell(3,  2, dr_D, 'Коридор', null, null),
          new Cell(3,  1, dr_D, 'Коридор', null, ['chest1dem1']),

          new Cell(4,  7, dr_LUR, 'Коридор', null, null),
          new Cell(4,  6, dr_RD, 'Коридор', null, ['stat2']),
          new Cell(4,  5, dr_LURD, 'Коридор', null, ['altar2']),
          new Cell(4,  4, dr_LR, 'Коридор', null, null),

          new Cell(5, 10, dr_U, 'Коридор', null, ['altar2']),
          new Cell(5,  9, dr_U, 'Коридор', [{name: 'sg', level:9, count: 2}], null),
          new Cell(5,  8, dr_UD, 'Коридор', null, null),
          new Cell(5,  7, dr_LURD, 'Коридор', [{name: 'stg', level:9, count: 2}], null),
          new Cell(5,  6, dr_LUD, 'Коридор', null, null),
          new Cell(5,  5, dr_UD, 'Коридор', null, null),
          new Cell(5,  4, dr_LURD, 'Коридор', [{name: 'stg', level:9, count: 2}], null),
          new Cell(5,  3, dr_UD, 'Коридор', null, null),
          new Cell(5,  2, dr_D, 'Коридор', [{name: 'sg', level:9, count: 2}], null),
          new Cell(5,  1, dr_D, 'Коридор', null, ['altar2']),

          new Cell(6,  7, dr_LR, 'Коридор', null, null),
          new Cell(6,  4, dr_LR, 'Коридор', null, null),

          new Cell(7, 10, dr_U, 'Коридор', null, ['antidotFountain']),
          new Cell(7,  9, dr_U, 'Коридор', null, null),
          new Cell(7,  8, dr_UD, 'Коридор', null, null),
          new Cell(7,  7, dr_LRD, 'Коридор', [{name: 'sg', level:9, count: 1},{name: 'sg', level:9, count: 1, alignment:1}], null),
          new Cell(7,  4, dr_LUR, 'Коридор', null, null),
          new Cell(7,  3, dr_UD, 'Коридор', null, null),
          new Cell(7,  2, dr_UD, 'Коридор', [{name: 'stg', level:9, count: 2},{name: 'rg', level:9, count: 2}], null),
          new Cell(7,  1, dr_D, 'Коридор', null, null),

          new Cell(8,  7, dr_LR, 'Коридор', null, null),
          new Cell(8,  6, dr_RD, 'Коридор', null, ['altar2']),
          new Cell(8,  4, dr_LR, 'Коридор', null, null),

          new Cell(9, 10, dr_U, 'Коридор', null, ['altar21']),
          new Cell(9,  9, dr_U, 'Коридор', [{name: 'stg', level:9, count: 1,alignment: 1}], null),
          new Cell(9,  8, dr_UD, 'Коридор', null, null),
          new Cell(9,  7, dr_LUD, 'Коридор', [{name: 'ep', level:9, count: 1}], null),
          new Cell(9,  6, dr_D, 'Коридор', null, null),
          new Cell(9,  4, dr_LUR, 'Коридор', [{name: 'ng', level:9, count: 1},{name: 'stg', level:9, count: 1},{name: 'sg', level:9, count: 1},{name: 'rg', level:9, count: 1}], null),
          new Cell(9,  3, dr_UD, 'Коридор', null, null),
          new Cell(9,  2, dr_UD, 'Коридор', null, null),
          new Cell(9,  1, dr_D, 'Коридор', null, ['proboina3']),

          new Cell(10,  7,dr_L, 'Коридор', null, ['altar2']),
          new Cell(10,  6,dr_L, 'Коридор', null, ['chest5']),
          new Cell(10,  4,dr_L, 'Коридор', null, null),
          new Cell(10,  2,dr_L, 'Коридор', null, ['kkstoneepisk']),

          new Cell(13, 10,dr_R, 'Коридор', null, ['enterDem22']),
          new Cell(13,  7,dr_U, 'Коридор', null, ['chest12']),
          new Cell(13,  6,dr_UR, 'Коридор', null, null),
          new Cell(13,  5,dr_RD, 'Коридор', null, null),
          new Cell(13,  3,dr_UR, 'Коридор', null, null),
          new Cell(13,  2,dr_UD, 'Коридор', null, null),
          new Cell(13,  1,dr_RD, 'Коридор', [{name: 'rm', level:9, count: 1},{name: 'smm', level:9, count: 1},{name: 'sm', level:9, count: 1}], null),

          new Cell(14, 10,dr_LR, 'Коридор', [{name: 'sl', level:9, count: 1}], null),
          new Cell(14,  8,dr_R, 'Коридор', null, null),
          new Cell(14,  6,dr_LU, 'Коридор', null, null),
          new Cell(14,  5,dr_LRD, 'Коридор', [{name: 'sm', level:9, count: 1, alignment:1}], null),
          new Cell(14,  3,dr_LR, 'Коридор', null, null),
          new Cell(14,  2,dr_LURD, 'Коридор', null, ['garbage']),
          new Cell(14,  1,dr_LR, 'Коридор', null, null),

          new Cell(15, 10,dr_LUR, 'Коридор', [{name: 'rm', level:8, count: 2},{name: 'smm', level:9, count: 1}], null),
          new Cell(15,  9,dr_UD, 'Коридор', null, null),
          new Cell(15,  8,dr_D, 'Коридор', [{name: 'sl', level:9, count: 1}], null),
          new Cell(15,  7,dr_D, 'Коридор', null, ['garbage']),
          new Cell(15,  5,dr_LUR, 'Коридор', null, null),
          new Cell(15,  4,dr_UD, 'Коридор', null, null),
          new Cell(15,  3,dr_LD, 'Коридор', [{name: 'rm', level:9, count: 2}], null),
          new Cell(15,  2,  dr_O, 'Коридор', null, ['stat3']),
          new Cell(15,  1,dr_LR, 'Коридор', null, ['danger03']),

          new Cell(16, 10,dr_LR, 'Коридор', null, ['danger021']),
          new Cell(16,  8,dr_L, 'Коридор', null, null),
          new Cell(16,  6,dr_UR, 'Коридор', [{name: 'sl', level:9, count: 2}], null),
          new Cell(16,  5,dr_LD, 'Коридор', [{name: 'sl', level:9, count: 2}], null),
          new Cell(16,  3,dr_LUR, 'Коридор', null, ['garbage']),
          new Cell(16,  2,dr_UR, 'Коридор', null, null),
          new Cell(16,  1,dr_RD, 'Коридор', null, null),

          new Cell(17, 10,dr_LR, 'Коридор', null, null),
          new Cell(17,  7,dr_U, 'Коридор', null, ['garbage']),
          new Cell(17,  6,dr_LR, 'Коридор',  [{name: 'rm', level:9, count: 2},{name: 'sm', level:8, count: 2}], null),
          new Cell(17,  3,dr_UR, 'Коридор', null, null),
          new Cell(17,  2,dr_LUD, 'Коридор', [{name: 'rm', level:9, count: 2},{name: 'sm', level:9, count: 2}], null),
          new Cell(17,  1,dr_LRD, 'Коридор', null, null),

          new Cell(18, 10,dr_LU, 'Коридор', null, ['danger011']),
          new Cell(18,  9,dr_RD, 'Коридор', [{name: 'sl', level:9, count: 3}], null),
          new Cell(18,  6,dr_LU, 'Коридор', null, null),
          new Cell(18,  5,dr_RD, 'Коридор', null, null),
          new Cell(18,  3,dr_LR, 'Коридор', [{name: 'sl', level:9, count: 2}], null),
          new Cell(18,  2,  dr_O, 'Коридор', null, ['danger022']),
          new Cell(18,  1,dr_LR, 'Коридор', null, null),


          new Cell(19,  9,dr_LR, 'Коридор', null, null),
          new Cell(19,  5,dr_LR, 'Коридор', null, null),
          new Cell(19,  3,dr_LR, 'Коридор', [{name: 'hsl', level:9, count: 1}], null),
          new Cell(19,  2,  dr_O, 'Коридор', null, ['garbage']),
          new Cell(19,  1,dr_LR, 'Коридор', [{name: 'rm', level:9, count: 1, alignment:1}], null),

          new Cell(20, 10,dr_U, 'Коридор', [{name: 'sm', level:9, count: 2}], null),
          new Cell(20,  9,dr_LURD, 'Коридор', [{name: 'sl', level:9, count: 1}], null),
          new Cell(20,  8,dr_RD, 'Коридор', null, null),
          new Cell(20,  6,dr_UR, 'Коридор', [{name: 'sl', level:9, count: 1}], null),
          new Cell(20,  5,dr_LRD, 'Коридор', null, null),
          new Cell(20,  3,dr_LR, 'Коридор', null, null),
          new Cell(20,  1,dr_LR, 'Коридор', [{name: 'chk', level:9, count: 1}], null),

          new Cell(21, 10,dr_LU, 'Коридор', null, ['ghostPowerFountain']),
          new Cell(21,  9,dr_LU, 'Коридор', null, ['stat1']),
          new Cell(21,  8,dr_LUD, 'Коридор', null, null),
          new Cell(21,  7,dr_UD, 'Коридор', [{name: 'rm', level:8, count: 2},{name: 'sm', level:9, count: 1},{name: 'smm', level:9, count: 1}], null),
          new Cell(21,  6,dr_LUD, 'Коридор', null, null),
          new Cell(21,  5,dr_LD, 'Коридор', null, null),
          new Cell(21,  4,  dr_O, 'Коридор', null, ['garbage']),
          new Cell(21,  3,dr_L, 'Коридор', [{name: 'sl', level:9, count: 2}], null),
          new Cell(21,  2,dr_U, 'Коридор', null, ['kkstonechern']),
          new Cell(21,  1,dr_LR, 'Коридор', null, ['chest51']),

          new Cell(22,  6,dr_L, 'Коридор', null, ['garbage']),
          new Cell(22,  3,dr_L, 'Коридор', null, ['chest22']),
          new Cell(22,  1,dr_L, 'Коридор', null, ['proboina4'])
       ]),

       // 3й этаж
       new Floor(3, [
          new Cell(1, 20, dr_R, 'Коридор', null, ['enterDem31']),
          new Cell(1, 16, dr_R, 'Коридор', null, null),
          new Cell(1, 14, dr_UR, 'Коридор', null, ['garbage']),
          new Cell(1, 13, dr_UR, 'Коридор', null, null),
          new Cell(1, 12, dr_UD, 'Коридор', [{name: 'zmb', level:10, count: 1}], null),
          new Cell(1, 11, dr_UD, 'Коридор', null, null),
          new Cell(1, 10, dr_RD, 'Коридор', null, null),
          new Cell(1,  7, dr_R, 'Коридор', null, ['teleportdem31']),
          new Cell(1,  4, dr_R, 'Коридор', null, ['garbage']),
          new Cell(1,  2, dr_UR, 'Коридор', null, ['drainbottom2']),
          new Cell(1,  1, dr_D, 'Коридор', null, ['enterDem32']),

          new Cell(2, 21, dr_U, 'Коридор', null, null),
          new Cell(2, 20, dr_LURD, 'Коридор', null, null),
          new Cell(2, 19, dr_UD, 'Коридор', [{name: 'zmb', level:10, count: 2}], null),
          new Cell(2, 18, dr_UD, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(2, 17, dr_UD, 'Коридор', [{name: 'zmb', level:10, count: 1}], null),
          new Cell(2, 16, dr_LRD, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(2, 14, dr_UR, 'Коридор', [{name: 'zmb', level:10, count: 1}], null),
          new Cell(2, 13, dr_LRD, 'Коридор', null, null),
          new Cell(2, 10, dr_L, 'Коридор', null, null),
          new Cell(2,  9,   dr_O, 'Коридор', null, ['barrikadadem3']),
          new Cell(2,  8, dr_UR, 'Коридор', null, ['chestdem32']),
          new Cell(2,  7, dr_R, 'Коридор', null, ['kkstoneshut']),
          new Cell(2,  6, dr_RD, 'Коридор', null, ['chestdem32']),
          new Cell(2,  5,   dr_O, 'Коридор', null, ['barrikadadem3']),
          new Cell(2,  4, dr_U, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(2,  3, dr_URD, 'Коридор', null, null),
          new Cell(2,  2, dr_LD, 'Коридор', [{name: 'prok', level:10, count: 2}], null),

          new Cell(3, 20, dr_LR, 'Коридор', [{name: 'zmb', level:10, count: 2}], null),
          new Cell(3, 18, dr_LR, 'Коридор', null, ['garbage']),
          new Cell(3, 16, dr_LR, 'Коридор', [{name: 'zmb', level:10, count: 2}], null),
          new Cell(3, 14, dr_LUR, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(3, 13, dr_LUD, 'Коридор', null, null),
          new Cell(3, 12, dr_RD, 'Коридор', [{name: 'pp', level:10, count: 2}], null),
          new Cell(3,  8, dr_U, 'Коридор', null, null),
          new Cell(3,  7, dr_LURD, 'Коридор', [{name: 'shp', level:10, count: 1}], null),
          new Cell(3,  6, dr_D, 'Коридор', null, null),
          new Cell(3,  3, dr_LR, 'Коридор', null, null),
          new Cell(3,  1, dr_R, 'Коридор', null, ['demFountain31']),

          new Cell(4, 20, dr_LR, 'Коридор', null, null),
          new Cell(4, 18, dr_R, 'Коридор', null, null),
          new Cell(4, 16, dr_LR, 'Коридор', null, null),
          new Cell(4, 14, dr_LR, 'Коридор', null, null),
          new Cell(4, 12, dr_LUR, 'Коридор', [{name: 'zmb', level:10, count: 2}], null),
          new Cell(4, 11, dr_UD, 'Коридор', null, null),
          new Cell(4, 10, dr_D, 'Коридор', null, null),
          new Cell(4,  9, dr_RD, 'Коридор', null, ['skelet31']),
          new Cell(4,  7, dr_LR, 'Коридор', null, null),
          new Cell(4,  4, dr_UR, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(4,  3, dr_LUD, 'Коридор', [{name: 'zmb', level:10, count: 1},{name: 'prok', level:10, count: 1}], null),
          new Cell(4,  2, dr_UD, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(4,  1, dr_D, 'Коридор', null, null),

          new Cell(5, 20, dr_LUR, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(5, 19, dr_UD, 'Коридор', null, null),
          new Cell(5, 18, dr_LRD, 'Коридор', [{name: 'zmb', level:10, count: 2}], null),
          new Cell(5, 16, dr_LU, 'Коридор', [{name: 'zmb', level:10, count: 2},{name: 'zmb', level:10, count: 1, alignment:1}], null),
          new Cell(5, 15, dr_UD, 'Коридор', null, null),
          new Cell(5, 14, dr_LD, 'Коридор', [{name: 'zmb', level:10, count: 1, alignment:1}], null),
          new Cell(5, 12, dr_LR, 'Коридор', null, null),
          new Cell(5,  9, dr_LU, 'Коридор', null, null),
          new Cell(5,  8, dr_R, 'Коридор', null, ['danger04']),
          new Cell(5,  7, dr_L, 'Коридор', null, ['danger041']),
          new Cell(5,  6, dr_U, 'Коридор', null, null),
          new Cell(5,  5, dr_UD, 'Коридор', [{name: 'prok', level:10, count: 2}], null),
          new Cell(5,  4, dr_LRD, 'Коридор', null, null),
          new Cell(5,  2, dr_L, 'Коридор', null, ['garbage']),

          new Cell(6, 20, dr_L, 'Коридор', null, null),
          new Cell(6, 18, dr_LR, 'Коридор', null, null),
          new Cell(6, 12, dr_LR, 'Коридор', null, null),
          new Cell(6,  8, dr_LR, 'Коридор', null, ['drainbottom2']),
          new Cell(6,  6, dr_L, 'Коридор', null, ['garbage']),
          new Cell(6,  4, dr_LR, 'Коридор', [{name: 'zmb', level:10, count: 2}], null),
          new Cell(6,  3, dr_D, 'Коридор', null, ['garbage']),
          new Cell(6,  1, dr_R, 'Коридор', null, ['chestdem31']),

          new Cell(7, 20, dr_L, 'Коридор', null, ['garbage']),
          new Cell(7, 18, dr_LR, 'Коридор', null, null),
          new Cell(7, 16, dr_R, 'Коридор', null, null),
          new Cell(7, 15, dr_D, 'Коридор', null, ['chestdem32']),
          new Cell(7, 14, dr_U, 'Коридор', null, null),
          new Cell(7, 13, dr_UD, 'Коридор', null, null),
          new Cell(7, 12, dr_LURD, 'Коридор', [{name: 'proksk', level:10, count: 2},{name: 'zmb', level:10, count: 1}], null),
          new Cell(7, 11, dr_UD, 'Коридор', null, null),
          new Cell(7, 10, dr_UD, 'Коридор', null, null),
          new Cell(7,  9, dr_UD, 'Коридор', [{name: 'prok', level:10, count: 1},{name: 'zmb', level:10, count: 2}], null),
          new Cell(7,  8, dr_LUD, 'Коридор', null, null),
          new Cell(7,  7, dr_RD, 'Коридор', null, null),
          new Cell(7,  5, dr_U, 'Коридор', null, null),
          new Cell(7,  4, dr_LRD, 'Коридор', [{name: 'bzmb', level:10, count: 1}], null),
          new Cell(7,  2, dr_UR, 'Коридор', null, ['dangerdem3']),
          new Cell(7,  1, dr_D, 'Коридор', null, null),

          new Cell(8, 20, dr_U, 'Коридор', null, null),
          new Cell(8, 19, dr_URD, 'Коридор', [{name: 'zmb', level:10, count: 1, alignment:1}], null),
          new Cell(8, 18, dr_LD, 'Коридор', null, null),
          new Cell(8, 16, dr_LR, 'Коридор', [{name: 'prp', level:10, count: 1}], null),
          new Cell(8, 15, dr_LRD, 'Коридор', null, ['fountdem31']),
          new Cell(8, 14, dr_L, 'Коридор', null, ['garbage']),
          new Cell(8, 12, dr_LR, 'Коридор', null, null),
          new Cell(8,  9, dr_LR, 'Коридор', null, ['barrikadadem3']),
          new Cell(8,  7, dr_L, 'Коридор', null, ['garbage']),
          new Cell(8,  4, dr_LR, 'Коридор', null, ['drainbottom2']),
          new Cell(8,  3, dr_URD, 'Коридор', null, ['garbage']),
          new Cell(8,  2, dr_LR, 'Коридор', null, null),

          new Cell(9, 20, dr_LU, 'Коридор', null, ['chest02dem3']),
          new Cell(9, 19, dr_LR, 'Коридор', null, null),
          new Cell(9, 16, dr_LR, 'Коридор', null, null),
          new Cell(9, 15, dr_LRD, 'Коридор', null, ['proboina5']),
          new Cell(9, 12, dr_LR, 'Коридор', null, ['drainbottom2']),
          new Cell(9,  9, dr_R, 'Коридор', null, null),
          new Cell(9,  6, dr_UR, 'Коридор', null, ['drainbottom2'] ),
          new Cell(9,  5, dr_UD, 'Коридор', null, null),
          new Cell(9,  4, dr_LUD, 'Коридор', [{name: 'zmb', level:10, count: 2},{name: 'prok', level:10, count: 1}], null),
          new Cell(9,  3, dr_UD, 'Коридор', null, null),
          new Cell(9,  2, dr_LRD, 'Коридор', [{name: 'trp', level:10, count: 1}], null),

          new Cell(10, 19,dr_LU, 'Коридор', null, ['enterDem33']),
          new Cell(10, 18,dr_UD, 'Коридор', null, null),
          new Cell(10, 17,dr_UD, 'Коридор', null, null),
          new Cell(10, 16,dr_LUD, 'Коридор', [{name: 'zmb', level:10, count: 2},{name: 'prok', level:10, count: 1}], null),
          new Cell(10, 15,dr_UD, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(10, 14,dr_UD, 'Коридор', [{name: 'bzmb', level:10, count: 1}], null),
          new Cell(10, 13,dr_UD, 'Коридор', [{name: 'prok', level:10, count: 2}], null),
          new Cell(10, 12,dr_LUD, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(10, 11,dr_UD, 'Коридор', null, ['drainbottom2']),
          new Cell(10, 10,dr_UD, 'Коридор', [{name: 'prok', level:10, count: 2}], null),
          new Cell(10,  9,dr_LUD, 'Коридор', null, null),
          new Cell(10,  8,dr_UD, 'Коридор', [{name: 'pp', level:10, count: 1}], null),
          new Cell(10,  7,dr_UD, 'Коридор', [{name: 'prok', level:10, count: 2}], null),
          new Cell(10,  6,dr_LD, 'Коридор', null, null),
          new Cell(10,  4,dr_L, 'Коридор', null, ['barrikadadem3']),
          new Cell(10,  2,dr_L, 'Коридор', null, null),
          new Cell(10,  1,dr_D, 'Коридор', null, ['garbage'])
       ]),

       // 4й этаж
       new Floor(4, [
          new Cell(0,  1, dr_R, 'Коридор', [{name: 'vilgol', level:11, count: 1}], ['kuzndem']),

          new Cell(1, 10, dr_R, 'Коридор', [{name: 'zmb', level:10, count: 2, alignment:1}], null),
          new Cell(1,  9, dr_URD, 'Коридор', null, ['lab2']),
          new Cell(1,  8, dr_R, 'Коридор', [{name: 'zmb', level:10, count: 2, alignment:1}], null),
          new Cell(1,  4,   dr_O, 'Коридор', null, ['gobelin03']),
          new Cell(1,  3, dr_UR, 'Коридор', null, ['chestdem41']),
          new Cell(1,  2, dr_UR, 'Коридор', null, ['danger07']),
          new Cell(1,  1, dr_RD, 'Коридор', null, null),

          new Cell(2, 10, dr_LUR, 'Коридор', [{name: 'zmb', level:10, count: 2, alignment:1}], null),
          new Cell(2,  9, dr_URD, 'Коридор', [{name: 'drs', level:10, count: 1}], null),
          new Cell(2,  8, dr_LRD, 'Коридор', [{name: 'zmb', level:10, count: 2, alignment:1}], null),
          new Cell(2,  4,   dr_O, 'Коридор', null, ['throne01']),
          new Cell(2,  3, dr_U, 'Коридор', [{name: 'pk', level:10, count: 1}], null),
          new Cell(2,  2, dr_LURD, 'Коридор', null, ['danger07']),
          new Cell(2,  1, dr_LRD, 'Коридор', null, ['vumpel01']),

          new Cell(3, 10, dr_LUR, 'Коридор', [{name: 'prok', level:10, count: 1, alignment:1}], null),
          new Cell(3,  9, dr_LURD, 'Коридор', null, null),
          new Cell(3,  8, dr_LRD, 'Коридор', [{name: 'prok', level:10, count: 1, alignment:1}], null),
          new Cell(3,  4,   dr_O, 'Коридор', null, ['gobelin02']),
          new Cell(3,  3, dr_LU, 'Коридор', null, ['chestdem42']),
          new Cell(3,  2, dr_LU, 'Коридор', null, null),
          new Cell(3,  1, dr_LRD, 'Коридор', null, null),

          new Cell(4, 10, dr_LU, 'Коридор', null, null),
          new Cell(4,  9, dr_LURD, 'Коридор', [{name: 'prok', level:10, count: 2, alignment:1}], null),
          new Cell(4,  8, dr_LD, 'Коридор', null, null),
          new Cell(4,  1, dr_L, 'Коридор', null, null),

          new Cell(5,  9, dr_LR, 'Коридор', [{name: 'bzmb', level:10, count: 1}], null),
          new Cell(5,  4, dr_UR, 'Коридор', [{name: 'drs', level:10, count: 1, alignment:1}], null),
          new Cell(5,  3, dr_URD, 'Коридор', null, null),
          new Cell(5,  2, dr_URD, 'Коридор', [{name: 'drs', level:10, count: 1, alignment:1}], null),
          new Cell(5,  1, dr_RD, 'Коридор', null, ['door3']),

          new Cell(6,  9, dr_LUR, 'Коридор', [{name: 'prok', level:10, count: 3, alignment:1}], null),
          new Cell(6,  8, dr_D, 'Коридор', null, null),
          new Cell(6,  7, dr_D, 'Коридор', null, ['altar2']),
          new Cell(6,  6, dr_UR, 'Коридор', null, null),
          new Cell(6,  5, dr_UD, 'Коридор', null, null),
          new Cell(6,  4, dr_LURD, 'Коридор', null, null),
          new Cell(6,  3, dr_LURD, 'Коридор', null, null),
          new Cell(6,  2, dr_LURD, 'Коридор', null, null),
          new Cell(6,  1, dr_LD, 'Коридор', [{name: 'drs', level:10, count: 1, alignment:1}], null),

          new Cell(7,  9, dr_LR, 'Коридор', [{name: 'bzmb', level:10, count: 1}], null),
          new Cell(7,  6, dr_LR, 'Коридор', [{name: 'prok', level:10, count: 2, alignment:1}], null),
          new Cell(7,  4, dr_LU, 'Коридор', [{name: 'drs', level:10, count: 1, alignment:1}], null),
          new Cell(7,  3, dr_LUD, 'Коридор', null, null),
          new Cell(7,  2, dr_LD, 'Коридор', [{name: 'drs', level:10, count: 1, alignment:1}], null),
          new Cell(7,  1, dr_LD, 'Коридор', null, ['chestdem43']),

          new Cell(8,  9, dr_LUR, 'Коридор', [{name: 'prok', level:10, count: 3, alignment:1}], null),
          new Cell(8,  8, dr_UD, 'Коридор', null, null),
          new Cell(8,  7, dr_URD, 'Коридор', [{name: 'bzmb', level:10, count: 1}], null),
          new Cell(8,  6, dr_LD, 'Коридор', null, null),
          new Cell(8,  4, dr_UR, 'Коридор', null, null),
          new Cell(8,  3, dr_URD, 'Коридор', [{name: 'drs', level:10, count: 1}], null),
          new Cell(8,  2, dr_URD, 'Коридор', null, null),
          new Cell(8,  1, dr_D, 'Коридор', [{name: 'drs', level:10, count: 1}], null),

          new Cell(9,  9, dr_LR, 'Коридор', null, null),
          new Cell(9,  7, dr_LR, 'Коридор', null, null),
          new Cell(9,  4, dr_LUR, 'Коридор', [{name: 'drs', level:10, count: 1}], null),
          new Cell(9,  3, dr_LURD, 'Коридор', null, null),
          new Cell(9,  2, dr_LRD, 'Коридор', null, ['danger06']),
          new Cell(9,  1, dr_LRD, 'Коридор', null, ['altar4']),

          new Cell(10, 10,dr_U, 'Коридор', null, ['enterDem41']),
          new Cell(10,  9,dr_LUD, 'Коридор', [{name: 'bzmb', level:10, count: 1}], null),
          new Cell(10,  8,dr_D, 'Коридор', null, null),
          new Cell(10,  7,dr_LU, 'Коридор', [{name: 'bzmb', level:10, count: 1}], null),
          new Cell(10,  6,dr_UD, 'Коридор', [{name: 'prok', level:10, count: 2, alignment:1}], null),
          new Cell(10,  5,dr_UD, 'Коридор', null, null),
          new Cell(10,  4,dr_LUD, 'Коридор', null, null),
          new Cell(10,  3,dr_LUD, 'Коридор', [{name: 'drs', level:10, count: 1}], null),
          new Cell(10,  2,dr_LUD, 'Коридор', null, null),
          new Cell(10,  1,dr_D, 'Коридор', [{name: 'drs', level:10, count: 1}], null)
       ])
   ]),

    new Dungeon('ПТП', [
        // 1й этаж
        new Floor(1, [
            new Cell(6, 10, dr_LU, 'Коридор', null, ['input']),
            new Cell(5, 10, dr_R, 'Коридор', null, ['teleport124']),

            new Cell(8, 9, dr_LU, 'Коридор', null, null),
            new Cell(7, 9, dr_LR, 'Коридор', [{name: 'pg', level:6, count: 2}], null),
            new Cell(6, 9, dr_URD, 'Коридор', null, null),

            new Cell(9, 8, dr_LU, 'Коридор', [{name: 'pm', level:7, count: 3}], null),
            new Cell(8, 8, dr_RD, 'Коридор', null, null),
            new Cell(6, 8, dr_LUD, 'Коридор', [{name: 'pu', level:7, count: 3}], null),
            new Cell(5, 8, dr_UR, 'Серпантин', [{name: 'pg', level: 7, count: 1}], null),
            new Cell(4, 8, dr_UR, 'Серпантин', null, null),
            new Cell(3, 8, dr_LUR, 'Серпантин', null, ['oneWayPass']),
            new Cell(2, 8, dr_LR, 'Серпантин', null, null),
            new Cell(1, 8, dr_R, 'Серпантин', [{name: 'pa', level:8, count: 1},{name: 'pm', level:7, count: 3, alignment: 1}], null),

            new Cell(10,7, dr_L, 'Логово', [{name: 'pm', level:6, count: 10}, {name: 'pg', level:7, count: 2}], null),
            new Cell(9, 7, dr_URD, 'Логово', [{name: 'pm', level:7, count: 5}], null),
            new Cell(6, 7, dr_UD, 'Коридор', [{name: 'pg', level:7, count: 1}], null),
            new Cell(4, 7, dr_UD, 'Серпантин', [{name: 'pm', level:7, count: 2}], null),
            new Cell(3, 7, dr_UD, 'Серпантин', null, null),
            new Cell(1, 7, dr_D, 'Фонтан Океана', null, ['oceanFountain']),

            new Cell(10,6, dr_LUD, 'Ключ к Фонтану Океана', null, ['key1']),
            new Cell(9, 6, dr_UD, 'Логово', [{name: 'pm', level:7, count: 2},{name: 'pu', level:7, count: 3}], null),
            new Cell(7, 6, dr_LU, 'Коридор', null, null),
            new Cell(6, 6, dr_RD, 'Коридор', null, null),
            new Cell(4, 6, dr_UD, 'Серпантин', null, null),
            new Cell(3, 6, dr_UD, 'Серпантин', [{name: 'pg', level:6, count: 8}], null),

            new Cell(10,5, dr_L, 'Логово', [{name: 'pu', level:6, count: 6}], null),
            new Cell(9, 5, dr_RD, 'Логово', [{name: 'pm', level:7, count: 1},{name: 'pa', level:8, count: 1}], null),
            new Cell(7, 5, dr_UD, 'Коридор', null, null),
            new Cell(5, 5, dr_LU, 'Серпантин', [{name: 'pu', level:7, count: 3}], null),
            new Cell(4, 5, dr_RD, 'Серпантин', null, null),
            new Cell(3, 5, dr_LD, 'Серпантин', [{name: 'pu', level:6, count: 5}], null),
            new Cell(2, 5, dr_UR, 'Серпантин', null, null),

            new Cell(7, 4, dr_UD, 'Коридор', [ {name: 'pm', level:7, count: 2}], null),
            new Cell(5, 4, dr_UD, 'Серпантин', null, null),
            new Cell(2, 4, dr_UD, 'Серпантин', null, null),

            new Cell(7, 3, dr_UD, 'Коридор', [{name: 'pg', level:7, count: 1, alignment: 1}], null),
            new Cell(5, 3, dr_LD, 'Серпантин', null, null),
            new Cell(4, 3, dr_LR, 'Серпантин', null, null),
            new Cell(3, 3, dr_LR, 'Серпантин', [{name: 'pm', level:7, count: 1}], null),
            new Cell(2, 3, dr_RD, 'Серпантин', [{name: 'pg', level:8, count: 1}], null),

            new Cell(8, 2, dr_L, 'Спуск', null, ['firstFloorLadder']),
            new Cell(7, 2, dr_RD, 'Коридор', [{name: 'pa', level:8, count: 1}], null)
        ]),
        // 2й этаж
        new Floor(2, [
            new Cell(8, 9, dr_U, 'Коридор', null, ['input']),
            new Cell(3, 9, dr_L, 'Коридор', null, null),
            new Cell(2, 9, dr_LR, 'Коридор', [{name: 'pa', level:9, count: 1}], ['key2']),
            new Cell(1, 9, dr_R, 'Коридор', null, ['teleport3']),

            new Cell(9, 8, dr_LU, 'Коридор', [{name: 'pg', level:8, count: 1}], null),
            new Cell(8, 8, dr_LRD, 'Коридор', null, null),
            new Cell(7, 8, dr_LR, 'Коридор', [{name: 'dk', level:8, count: 1}], null),
            new Cell(6, 8, dr_LUR, 'Логово', [{name: 'pm', level:7, count: 3}], null),
            new Cell(5, 8, dr_LR, 'Логово', [{name: 'pm', level:8, count: 1}], null),
            new Cell(4, 8, dr_UR, 'Логово', [{name: 'pm', level:7, count: 8}], null),

            new Cell(9, 7, dr_UD, 'Коридор', null, null),
            new Cell(6, 7, dr_UD, 'Логово', [{name: 'pm', level:8, count: 5}], null),
            new Cell(5, 7, dr_LURD, 'Логово', null, ['denyingFountain']),
            new Cell(4, 7, dr_LUD, 'Логово', [{name: 'pm', level:8, count: 2}], null),
            new Cell(3, 7, dr_LR, 'Коридор', null, null),
            new Cell(2, 7, dr_UR, 'Коридор', [{name: 'pg', level:8, count: 1}], null),

            new Cell(10,6, dr_LU, 'Коридор', null, null),
            new Cell(9, 6, dr_RD, 'Коридор', null, null),
            new Cell(6, 6, dr_LD, 'Логово', [{name: 'pa', level:8, count: 1},{name: 'pu', level:6, count: 15}], null),
            new Cell(5, 6, dr_LUR, 'Логово', [{name: 'pm', level:6, count: 15},{name: 'pa', level:8, count: 1}], null),
            new Cell(4, 6, dr_RD, 'Логово', [{name: 'pa', level:8, count: 1, alignment: 1},{name: 'pm', level:7, count: 3,  alignment: 1}], null),
            new Cell(2, 6, dr_UD, 'Коридор', null, null),

            new Cell(10,5, dr_UD, 'Коридор', [{name: 'pu', level:8, count: 3},{name: 'pm', level:8, count: 1}], null),
            new Cell(7, 5, dr_U, 'Коридор', [{name: 'pu', level:8, count: 3}], null),
            new Cell(5, 5, dr_UD, 'Коридор', null, null),
            new Cell(2, 5, dr_UD, 'Коридор', [{name: 'pg', level:9, count: 2}], null),

            new Cell(10,4, dr_D, 'Коридор', [{name: 'pg', level:8, count: 2}], null),
            new Cell(8, 4, dr_L, 'Коридор', null, ['teleport1']),
            new Cell(7, 4, dr_LUD, 'Коридор', [{name: 'pm', level:8, count: 2}], null),
            new Cell(6, 4, dr_LR, 'Коридор', [{name: 'pg', level:7, count: 1}], null),
            new Cell(5, 4, dr_RD, 'Коридор', [{name: 'pg', level:9, count: 1}], null),
            new Cell(4, 4, dr_LU, 'Коридор', [{name: 'pg', level:8, count: 3}], null),
            new Cell(3, 4, dr_LR, 'Коридор', null, null),
            new Cell(2, 4, dr_URD, 'Коридор', [{name: 'pg', level:8, count: 2}], null),

            new Cell(10,3, dr_D, 'Коридор', null, ['teleport2']),
            new Cell(7, 3, dr_UD, 'Коридор', null, null),
            new Cell(4, 3, dr_UD, 'Коридор', [{name: 'pg', level:9, count: 1, alignment: 1}], null),
            new Cell(3, 3, dr_R, 'Коридор', null, ['oneWayPass']),
            new Cell(2, 3, dr_UD, 'Коридор', null, null),

            new Cell(7, 2, dr_LUD, 'Коридор', [{name: 'pu', level:8, count: 1}], null),
            new Cell(6, 2, dr_LR, 'Коридор', null, null),
            new Cell(5, 2, dr_LUR, 'Коридор', null, null),
            new Cell(4, 2, dr_LRD, 'Коридор', null, null),
            new Cell(3, 2, dr_LR, 'Коридор', null, null),
            new Cell(2, 2, dr_RD, 'Коридор', [{name: 'pu', level:8, count: 1}], null),

            new Cell(10,1, dr_R, 'Коридор', null, ['chest']),
            new Cell(9, 1, dr_R, 'Коридор', [{name: 'im', level:9, count: 1}], null),
            new Cell(8, 1, dr_LR, 'Коридор', [{name: 'pa', level:8, count: 1},{name: 'pu', level:8, count: 3}], null),
            new Cell(7, 1, dr_RD, 'Коридор', null, null),
            new Cell(5, 1, dr_D, 'Коридор', null, null),

            new Cell(8, 0, dr_D, 'Спуск', null, ['secondFloorLadder'])
        ]),
        // 3й этаж
        new Floor(3, [
            new Cell(9, 8, dr_LU, 'Коридор', null, null),
            new Cell(8, 8, dr_R, 'Вход', null, ['input']),
            new Cell(6, 8, dr_L, 'Коридор', null, ['teleport5']),
            new Cell(5, 8, dr_L, 'Коридор', [{name: 'sk', level:9, count: 1}], null),
            new Cell(4, 8, dr_LR, 'Коридор', null, null),
            new Cell(3, 8, dr_LR, 'Коридор', null, null),
            new Cell(2, 8, dr_LUR, 'Коридор', null, null),
            new Cell(1, 8, dr_R, 'Коридор', null, null),

            new Cell(9, 7, dr_UD, 'Коридор', [{name: 'pg', level:8, count: 1}], null),
            new Cell(7, 7, dr_U, 'Коридор', null, ['plusFifteenFountain'], ['key3']),
            new Cell(4, 7, dr_D, 'Коридор', null, ['teleport4']),
            new Cell(2, 7, dr_UD, 'Коридор', null, null),

            new Cell(10,6, dr_L, 'Коридор', null, null),
            new Cell(9, 6, dr_LURD, 'Коридор', null, null),
            new Cell(8, 6, dr_LR, 'Коридор', null, null),
            new Cell(7, 6, dr_LR, 'Коридор', [{name: 'pa', level:9, count: 1, alignment: 1}], null),
            new Cell(6, 6, dr_UR, 'Коридор', null, null),
            new Cell(3, 6, dr_LU, 'Коридор', [{name: 'pu', level:7, count: 3}], null),
            new Cell(2, 6, dr_LURD, 'Коридор', [{name: 'pg', level:7, count: 1}], null),
            new Cell(1, 6, dr_UR, 'Коридор', [{name: 'pm', level:7, count: 3}], null),
            //
            new Cell(9, 5, dr_UD, 'Коридор', null, null),
            new Cell(6, 5, dr_UD, 'Коридор', null, null),
            new Cell(3, 5, dr_LD, 'Коридор', [{name: 'pm', level:8, count: 3}], null),
            new Cell(2, 5, dr_LRD, 'Коридор', [{name: 'pa', level:8, count: 1}], null),
            new Cell(1, 5, dr_RD, 'Коридор', [{name: 'pu', level:8, count: 3}], null),
            //
            new Cell(10,4, dr_L, 'Коридор', null, ['lostMastersCupel']),
            new Cell(9, 4, dr_D, 'Коридор', [{name: 'ms',level:8,count:1}], null),
            new Cell(7, 4, dr_LU, 'Коридор', null, null),
            new Cell(6, 4, dr_LRD, 'Коридор',[{name:'pu',level:8,count:1, alignment:1},{name:'pa',level:8,count:1, alignment:1}],null),
            new Cell(5, 4, dr_UR, 'Коридор', [{name:'pm',level:8,count:1, alignment:1},{name:'pu',level:7,count:1, alignment:1}],null),

            new Cell(7, 3, dr_D, 'Коридор', [{name: 'pm', level:8, count: 2, alignment: 1}], null),
            new Cell(6, 3, dr_LRD, 'Коридор', null, ['greatDenyingFountain']),
            new Cell(5, 3, dr_D, 'Коридор', [{name: 'pm', level:8, count: 1, alignment: 1},{name: 'pu', level:7, count: 3, alignment: 1}], null)
        ]),
        // 4й этаж
        new Floor(4, [
            new Cell(14,18, dr_U, 'Вход', null, ['input']),
            new Cell(12,18, dr_U, 'Коридор', null, ['chestcap5']),
            new Cell(10,18, dr_LU, 'Коридор', [{name: 'pg', level:9, count: 3}], null),
            new Cell( 9,18, dr_LR, 'Коридор', [{name: 'pg', level:8, count: 4}], null),
            new Cell( 8,18, dr_UR, 'Коридор', null, null),
            new Cell( 6,18, dr_U, 'Коридор',  null, null),

            new Cell(14,17, dr_LD, 'Коридор', null, null),
            new Cell(13,17, dr_LR, 'Коридор', [{name: 'pg', level:8, count: 4},{name: 'pg', level:6, count: 1}], null),
            new Cell(12,17, dr_LUR, 'Коридор', null, null),
            new Cell(11,17, dr_LR, 'Коридор', [{name: 'pg', level:7, count: 3},{name: 'pg', level:8, count: 4}], null),
            new Cell(10,17, dr_RD, 'Коридор', [{name: 'dpg', level:9, count: 1},{name: 'pg', level:7, count: 4}], null),
            new Cell( 8,17, dr_LD, 'Коридор', [{name: 'pg', level:9, count: 3}], null),
            new Cell( 7,17, dr_LR, 'Коридор',  [{name: 'pg', level:7, count: 5}], null),
            new Cell( 6,17, dr_RD, 'Коридор',  null, null),
            new Cell( 5,17, dr_R, 'Коридор', null, ['teleportcap4']),

            new Cell(12,16, dr_D, 'Коридор', [{name: 'pg', level:8, count: 3}], null),
            new Cell( 6,16, dr_D, 'Коридор',  null, ['chestcap5']),

            new Cell(13,15, dr_R, 'Коридор', null, null),
            new Cell(12,15, dr_LUR, 'Коридор', [{name: 'kstr', level:9, count: 1}], null),
            new Cell(11,15, dr_R, 'Коридор', null, null),

            new Cell(13,14, dr_LD, 'Коридор', null, ['chestcap5']),
            new Cell(12,14, dr_UD, 'Коридор', null, ['danger09']),
            new Cell(11,14, dr_RD, 'Коридор', null, ['chestcap43']),

            new Cell(12,13, dr_UD, 'Коридор', null, null),

            new Cell(13,12, dr_LU, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell(12,12, dr_LRD, 'Коридор', null, null),
            new Cell(11,12, dr_LR, 'Коридор', [{name: 'brzldsh', level:10, count: 1}], null),
            new Cell(10,12, dr_LR, 'Коридор', null, ['danger042']),
            new Cell( 9,12, dr_L, 'Коридор', null, null),
            new Cell( 8,12, dr_LR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 7,12, dr_LR, 'Коридор', null, null),
            new Cell( 6,12, dr_LR, 'Коридор', null, null),
            new Cell( 5,12, dr_LR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 4,12, dr_LR, 'Коридор', null, ['weap2']),
            new Cell( 3,12, dr_LR, 'Коридор', null, null),
            new Cell( 2,12, dr_LR, 'Коридор', null, ['weap3']),
            new Cell( 1,12, dr_UR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),

            new Cell(13,11, dr_UD, 'Коридор', null, null),
            new Cell(11,11, dr_U, 'Коридор', null, ['chestcap41']),
            new Cell( 8,11, dr_L, 'Коридор', null, ['chestcap42']),
            new Cell( 7,11, dr_L, 'Коридор', [{name: 'mhk', level:9, count: 1},{name: 'mhgol', level:9, count: 2}], null),
            new Cell( 6,11, dr_LR, 'Коридор', null, null),
            new Cell( 5,11, dr_LR, 'Коридор', null, ['teleportcap42']),
            new Cell( 4,11, dr_LR, 'Коридор', null, ['weap3']),
            new Cell( 3,11, dr_UR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 1,11, dr_UD, 'Коридор', null, null),

            new Cell(13,10, dr_UD, 'Коридор', null, ['zerkalocap']),
            new Cell(12,10, dr_LU, 'Коридор', [{name: 'kzm', level:10, count: 2}], null),
            new Cell(11,10, dr_LUR, 'Коридор', null, ['danger08']),
            new Cell(10,10, dr_R, 'Коридор', [{name: 'gzm', level:10, count: 3}], null),
            new Cell( 7,10, dr_UD, 'Коридор', null, ['dangercap41']),
            new Cell( 3,10, dr_UD, 'Коридор', null, null),
            new Cell( 1,10, dr_UD, 'Коридор', null, null),

            new Cell(13, 9, dr_UD, 'Коридор', null, null),
            new Cell(12, 9, dr_LD, 'Коридор', null, null),
            new Cell(11, 9, dr_URD, 'Коридор', [{name: 'zldsh', level:10, count: 1}], null),
            new Cell(10, 9, dr_LU, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 9, 9, dr_LR, 'Коридор', null, null),
            new Cell( 8, 9, dr_LR, 'Коридор', [{name: 'brzldsh', level:10, count: 1}], null),
            new Cell( 7, 9, dr_LR, 'Коридор', null, null),
            new Cell( 6, 9, dr_LR, 'Коридор', null, null),
            new Cell( 5, 9, dr_LR, 'Коридор', null, null),
            new Cell( 4, 9, dr_UR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 3, 9, dr_UD, 'Коридор', null, null),
            new Cell( 1, 9, dr_UD, 'Коридор', null, ['zerkalocap']),

            new Cell(13, 8, dr_UD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell(11, 8, dr_UD, 'Коридор', null, null),
            new Cell(10, 8, dr_UD, 'Коридор', null, null),
            new Cell( 8, 8, dr_LU, 'Коридор', null, null),
            new Cell( 7, 8, dr_LUR, 'Коридор', null, ['zerkalocap']),
            new Cell( 6, 8, dr_UR, 'Коридор', [{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 4, 8, dr_UD, 'Коридор', null, null),
            new Cell( 3, 8, dr_UD, 'Коридор', null, null),
            new Cell( 1, 8, dr_UD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),

            new Cell(13, 7, dr_UD, 'Коридор', null, null ),
            new Cell(11, 7, dr_UD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell(10, 7, dr_LUD, 'Коридор', null, null),
            new Cell( 9, 7, dr_LR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 8, 7, dr_LURD, 'Коридор', null, null),
            new Cell( 7, 7, dr_LURD, 'Коридор', null, ['Enterlabirint']),
            new Cell( 6, 7, dr_LURD, 'Коридор', null, null),
            new Cell( 5, 7, dr_LR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 4, 7, dr_URD, 'Коридор', null, ['vumpel01']),
            new Cell( 3, 7, dr_UD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 1, 7, dr_UD, 'Коридор', null, null),

            new Cell(13, 6, dr_UD, 'Коридор', null, null),
            new Cell(11, 6, dr_UD, 'Коридор', null, null),
            new Cell(10, 6, dr_UD, 'Коридор', null, ['weap3']),
            new Cell( 8, 6, dr_LD, 'Коридор', [{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 7, 6, dr_LRD, 'Коридор', null, ['zerkalocap']),
            new Cell( 6, 6, dr_RD, 'Коридор', null, null),
            new Cell( 4, 6, dr_UD, 'Коридор', null, null),
            new Cell( 3, 6, dr_UD, 'Коридор', null, null),
            new Cell( 1, 6, dr_UD, 'Коридор', null, null),

            new Cell(13, 5, dr_UD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell(11, 5, dr_UD, 'Коридор', [{name: 'brzldsh', level:10, count: 1}], null),
            new Cell(10, 5, dr_LD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 9, 5, dr_LR, 'Коридор', null, ['gobelin02']),
            new Cell( 8, 5, dr_LR, 'Коридор', null, null),
            new Cell( 7, 5, dr_LUR, 'Коридор', [{name: 'dhr', level:10, count: 1}], null),
            new Cell( 6, 5, dr_LR, 'Коридор', null, null),
            new Cell( 5, 5, dr_LR, 'Коридор', [{name: 'brzldsh', level:10, count: 1}], null),
            new Cell( 4, 5, dr_RD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 3, 5, dr_UD, 'Коридор', [{name: 'brzldsh', level:10, count: 1}], null),
            new Cell( 1, 5, dr_UD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),

            new Cell(13, 4, dr_UD, 'Коридор', null, null),
            new Cell(11, 4, dr_UD, 'Коридор', null, null),
            new Cell( 7, 4, dr_UD, 'Коридор', null, null),
            new Cell( 3, 4, dr_UD, 'Коридор', null, null),
            new Cell( 1, 4, dr_UD, 'Коридор', null, null),

            new Cell(13, 3, dr_UD, 'Коридор', null, ['zerkalocap']),
            new Cell(11, 3, dr_LD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell(10, 3, dr_LR, 'Коридор', null, null),
            new Cell( 9, 3, dr_LUR, 'Коридор', [{name: 'odduxgol', level:11, count: 1}], null),
            new Cell( 8, 3, dr_LR, 'Коридор', null, null),
            new Cell( 7, 3, dr_LRD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 6, 3, dr_LR, 'Коридор', null, null),
            new Cell( 5, 3, dr_LR, 'Коридор', null, null),
            new Cell( 4, 3, dr_LR, 'Коридор', null, null),
            new Cell( 3, 3, dr_RD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 1, 3, dr_UD, 'Коридор', null, ['gobelin03']),

            new Cell(13, 2, dr_UD, 'Коридор', null, null),
            new Cell( 9, 2, dr_UD, 'Коридор', null, null),
            new Cell( 1, 2, dr_UD, 'Коридор', null, null),

            new Cell(13, 1, dr_LD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell(12, 1, dr_LR, 'Коридор', null, null),
            new Cell(11, 1, dr_LR, 'Коридор', [{name: 'brzldsh', level:10, count: 1}], null),
            new Cell(10, 1, dr_LR, 'Коридор', null, null),
            new Cell( 9, 1, dr_RD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 8, 1, dr_LR, 'Коридор', null, ['danger042']),
            new Cell( 7, 1, dr_LU, 'Коридор', null, ['zerkalocap']),
            new Cell( 6, 1, dr_LR, 'Коридор', null, null),
            new Cell( 5, 1, dr_LR, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),
            new Cell( 4, 1, dr_LR, 'Коридор', null, null),
            new Cell( 3, 1, dr_LR, 'Коридор', [{name: 'brzldsh', level:10, count: 1}], null),
            new Cell( 2, 1, dr_LR, 'Коридор', null, null),
            new Cell( 1, 1, dr_RD, 'Коридор', [{name: 'dhr', level:10, count: 1},{name: 'zldsh', level:10, count: 1}], null),

            new Cell( 7, 0, dr_UD, 'Коридор', null, ['laddercap45'])
        ]),
        // 5й этаж
        new Floor(5, [
            new Cell(11,15, dr_U, 'Коридор', null, ['chestcap531']),
            new Cell( 9,15, dr_U, 'Коридор', null, ['chestcap54']),
            new Cell( 7,15, dr_U, 'Коридор', null, ['chestcap541']),
            new Cell( 5,15, dr_U, 'Коридор', null, ['chestcap542']),
            new Cell( 3,15, dr_U, 'Коридор', null, ['chestcap532']),

            new Cell(11,14, dr_U, 'Коридор', [{name: 'strsokrs', level:11, count: 1, alignment:1}], null),
            new Cell( 9,14, dr_U, 'Коридор', [{name: 'strsokrl', level:11, count: 1, alignment:1}], null),
            new Cell( 7,14, dr_U, 'Коридор', [{name: 'strsokri', level:11, count: 1, alignment:1}], null),
            new Cell( 5,14, dr_U, 'Коридор', [{name: 'strsokril', level:11, count: 1, alignment:1}], null),
            new Cell( 3,14, dr_U, 'Коридор', [{name: 'strsokrv', level:11, count: 1, alignment:1}], null),

            new Cell(11,13, dr_LD, 'Коридор', null, null),
            new Cell(10,13, dr_LR, 'Коридор', null, null),
            new Cell( 9,13, dr_LRD, 'Коридор', null, null),
            new Cell( 8,13, dr_LR, 'Коридор', null, ['vumpel01']),
            new Cell( 7,13, dr_LURD, 'Коридор', null, null),
            new Cell( 6,13, dr_LR, 'Коридор', null, null),
            new Cell( 5,13, dr_LRD, 'Коридор', null, null),
            new Cell( 4,13, dr_LR, 'Коридор', null, ['vumpel01']),
            new Cell( 3,13, dr_RD, 'Коридор', null, null),

            new Cell( 7,12, dr_UD, 'Коридор', null, ['gard1']),
            new Cell( 6,12, dr_LU, 'Коридор', [{name: 'mhk', level:9, count: 2}], null),
            new Cell( 5,12, dr_LR, 'Коридор', null, null),
            new Cell( 4,12, dr_LR, 'Коридор', [{name: 'mhk', level:9, count: 1}], null),
            new Cell( 3,12, dr_LR, 'Коридор', [{name: 'mhk', level:9, count: 2},{name: 'mhgol', level:9, count: 1}], null),
            new Cell( 2,12, dr_UR, 'Коридор', [{name: 'mhub', level:10, count: 1} ], null),
            new Cell( 1,12, dr_UR, 'Коридор', null, ['altar5']),

            new Cell(12,11, dr_LU, 'Коридор', null, null),
            new Cell(11,11, dr_LR, 'Коридор', [{name: 'mhub', level:10, count: 1}], null),
            new Cell(10,11, dr_LUR, 'Коридор', null, null),
            new Cell( 9,11, dr_LR, 'Коридор', [{name: 'brmhgol', level:9, count: 1}], null),
            new Cell( 8,11, dr_LUR, 'Коридор', [{name: 'mhub', level:10, count: 1}], null),
            new Cell( 7,11, dr_RD, 'Коридор', null, null),
            new Cell( 6,11, dr_UD, 'Коридор', null, null),
            new Cell( 2,11, dr_LD, 'Коридор', [{name: 'mhk', level:9, count: 1}], null),
            new Cell( 1,11, dr_UR, 'Коридор', null, null),

            new Cell(12,10, dr_UD, 'Коридор', [{name: 'brmhgol', level:9, count: 1}], null),
            new Cell(10,10, dr_UD, 'Коридор', null, ['doorcap5']),
            new Cell( 8,10, dr_UD, 'Коридор', [{name: 'brmhgol', level:9, count: 1}], null),
            new Cell( 6,10, dr_UD, 'Коридор', null, null),
            new Cell( 1,10, dr_UD, 'Коридор', null, null),

            new Cell(12, 9, dr_UD, 'Коридор', null, null),
            new Cell(11, 9, dr_L, 'Коридор', null, ['grcrt']),
            new Cell(10, 9, dr_LRD, 'Коридор', [{name: 'mgrt', level:11, count: 1, alignment:1}], null),
            new Cell( 9, 9, dr_R, 'Коридор', null, ['pottbl']),
            new Cell( 8, 9, dr_LUD, 'Коридор', null, null),
            new Cell( 7, 9, dr_LR, 'Коридор', [{name: 'mhub', level:10, count: 1}], null),
            new Cell( 6, 9, dr_LRD, 'Коридор', null, null),
            new Cell( 5, 9, dr_LR, 'Коридор', null, null),
            new Cell( 4, 9, dr_UR, 'Коридор', [{name: 'mhohr', level:10, count: 3}], null),
            new Cell( 3, 9, dr_R, 'Коридор', null, ['chestcap5']),
            new Cell( 1, 9, dr_UD, 'Коридор', null, null),

            new Cell(12, 8, dr_UD, 'Коридор', [{name: 'mhohr', level:10, count: 1},{name: 'mhk', level:9, count: 3}], null),
            new Cell(11, 8, dr_D, 'Коридор', null, ['gralt']),
            new Cell(10, 8, dr_D, 'Коридор', null, ['chestcap5']),
            new Cell( 9, 8, dr_D, 'Коридор', null, ['gritlab']),
            new Cell( 8, 8, dr_UD, 'Коридор', [{name: 'brmhgol', level:9, count: 1}], null),
            new Cell( 4, 8, dr_UD, 'Коридор', null, null),
            new Cell( 1, 8, dr_UD, 'Коридор', null, null),

            new Cell(12, 7, dr_LUD, 'Коридор', null, ['dangercap51']),
            new Cell(11, 7, dr_LR, 'Коридор', [{name: 'mhgol', level:9, count: 3}], null),
            new Cell(10, 7, dr_LUR, 'Коридор', null, null),
            new Cell( 9, 7, dr_LR, 'Коридор', null, null),
            new Cell( 8, 7, dr_RD, 'Коридор', [{name: 'mhk', level:9, count: 1}], null),
            new Cell( 4, 7, dr_LD, 'Коридор', [{name: 'mhk', level:9, count: 2}], null),
            new Cell( 3, 7, dr_LR, 'Коридор', null, null),
            new Cell( 2, 7, dr_LR, 'Коридор', [{name: 'mhub', level:10, count: 1} ], null),
            new Cell( 1, 7, dr_RD, 'Коридор', [{name: 'mhk', level:9, count: 1},{name: 'mhub', level:10, count: 1} ], null),

            new Cell(19, 6, dr_U, 'Коридор', null, ['laddercap5']),
            new Cell(18, 6, dr_U, 'Коридор', null, null),
            new Cell(17, 6, dr_LUR, 'Коридор', null, ['chestcap5']),
            new Cell(16, 6, dr_U, 'Коридор', null, null),
            new Cell(15, 6, dr_LU, 'G11', [{name: 'mhgol', level:9, count: 2},{name: 'mhohr', level:10, count: 1},{name: 'mhk', level:9, count: 1}], null),
            new Cell(14, 6, dr_UR, 'Коридор', null, null),
            new Cell(13, 6, dr_UR, 'Коридор', null, ['chestcap5']),
            new Cell(12, 6, dr_UD, 'Коридор', null, null),
            new Cell(10, 6, dr_UD, 'Коридор', [{name: 'mhgol', level:9, count: 1},{name: 'mhohr', level:10, count: 3}], null),

            new Cell(19, 5, dr_UD, 'Коридор', [{name: 'mhub', level:10, count: 1}], null),
            new Cell(18, 5, dr_LD, 'Коридор', [{name: 'mhohr', level:10, count: 2},{name: 'mhk', level:9, count: 1}], null),
            new Cell(17, 5, dr_LUR, 'Коридор', null, null),
            new Cell(16, 5, dr_RD, 'Коридор', [{name: 'mhgol', level:9, count: 1},{name: 'mhub', level:10, count: 1}], null),
            new Cell(15, 5, dr_LD, 'Коридор', null, null),
            new Cell(14, 5, dr_LURD, 'Коридор', [{name: 'mhohr', level:10, count: 4}], null),
            new Cell(13, 5, dr_R, 'Коридор', null, null),
            new Cell(12, 5, dr_UD, 'Коридор', null, null),
            new Cell(11, 5, dr_LU, 'Коридор', [{name: 'mhgol', level:9, count: 2},{name: 'mhk', level:9, count: 1}], null),
            new Cell(10, 5, dr_LURD, 'Коридор', null, null),
            new Cell( 9, 5, dr_UR, 'Коридор', [{name: 'mhgol', level:9, count: 2},{name: 'mhohr', level:10, count: 1}], null),
            new Cell( 8, 5, dr_R, 'Коридор', null, ['chestcap52']),

            new Cell(19, 4, dr_UD, 'Коридор', null, null),
            new Cell(17, 4, dr_UD, 'Коридор', null, null),
            new Cell(14, 4, dr_UD, 'Коридор', null, null),
            new Cell(12, 4, dr_UD, 'Коридор', null, null),
            new Cell(11, 4, dr_LD, 'Коридор', [{name: 'mhgol', level:9, count: 3}], null),
            new Cell(10, 4, dr_LRD, 'Коридор', null, null),
            new Cell( 9, 4, dr_URD, 'Коридор', [{name: 'mhub', level:10, count: 1}], null),

            new Cell(19, 3, dr_LD, 'Коридор', [{name: 'mhgol', level:9, count: 4}], null),
            new Cell(18, 3, dr_LR, 'Коридор', null, null),
            new Cell(17, 3, dr_LRD, 'Коридор', [{name: 'mhk', level:9, count: 3}], null),
            new Cell(16, 3, dr_LR, 'Коридор', null, ['zerkalocap']),
            new Cell(15, 3, dr_LR, 'Коридор', null, ['zerkalocap']),
            new Cell(14, 3, dr_LRD, 'Коридор', [{name: 'mhgol', level:9, count: 1},{name: 'mhk', level:9, count: 1}], null),
            new Cell(13, 3, dr_LR, 'Коридор', null, null),
            new Cell(12, 3, dr_RD, 'Коридор', [{name: 'mhub', level:10, count: 1}], null),
            new Cell( 9, 3, dr_UD, 'Коридор', null, null),


            new Cell(10, 2, dr_L, 'Коридор', [{name: 'mhub', level:10, count: 2}], null),
            new Cell( 9, 2, dr_URD, 'Коридор', null, null),


            new Cell(10, 1, dr_LD, 'Коридор', null, ['chestcap51']),
            new Cell( 9, 1, dr_LD, 'Коридор', null, ['dangercap5']),
            new Cell( 8, 1, dr_R, 'Коридор', [{name: 'mhohr', level:10, count: 3},{name: 'mhk', level:9, count: 1}], null)
        ])
    ])
]);
