var routes = {
    1: {
        v1: {
            start: [1, 22],
            route: [
                {move: ['f', 'c'], result: {x: 1, y: 21, direction: 'N'}},
                {move: ['f', 'tr'], result: {x: 1, y: 20, direction: 'E'}},
                {move: ['f'], result: {x: 2, y: 20, direction: 'E'}},
                {move: ['f'], result: {x: 3, y: 20, direction: 'E'}},
                {move: ['f'], result: {x: 4, y: 20, direction: 'E'}},
                {move: ['f', 'c'], result: {x: 5, y: 20, direction: 'E'}},
                {move: ['tl', 'l'], result: {x: 4, y: 20, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 19, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 18, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 4, y: 17, direction: 'W'}},
                {move: ['f', 'tl', 'c', 'tr'], result: {x: 3, y: 17, direction: 'W'}},
                {move: ['f', 'tl'], result: {x: 2, y: 17, direction: 'S'}},
                {move: ['f', 'tr'], result: {x: 2, y: 18, direction: 'W'}},
                {move: ['f', 'tr'], result: {x: 1, y: 18, direction: 'N'}},
                {move: ['f'], result: {x: 1, y: 17, direction: 'N'}},
                {move: ['f'], result: {x: 1, y: 16, direction: 'N'}},
                {move: ['f', 'c', 'tl', 'tl'], result: {x: 1, y: 15, direction: 'S'}},
                {move: ['f'], result: {x: 1, y: 16, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 1, y: 17, direction: 'E'}},
                {move: ['f'], result: {x: 2, y: 17, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 3, y: 17, direction: 'N'}},
                {move: ['f'], result: {x: 3, y: 16, direction: 'N'}},
                {move: ['f', 'tl', 'tl'], result: {x: 3, y: 15, direction: 'S'}},
                {move: ['f'], result: {x: 3, y: 16, direction: 'S'}},
                {move: ['f', 'tl'], result: {x: 3, y: 17, direction: 'E'}},
                {move: ['f'], result: {x: 4, y: 17, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 4, y: 17, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 16, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 15, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 14, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 13, direction: 'N'}},
                {move: ['f', 'tl', 'tl'], result: {x: 4, y: 12, direction: 'S'}},
                {move: ['f'], result: {x: 4, y: 13, direction: 'S'}},
                {move: ['f'], result: {x: 4, y: 14, direction: 'S'}},
                {move: ['f'], result: {x: 4, y: 15, direction: 'S'}},
                {move: ['f'], result: {x: 4, y: 16, direction: 'S'}},
                {move: ['f', 'tl'], result: {x: 4, y: 17, direction: 'E'}},
                {move: ['f'], result: {x: 5, y: 17, direction: 'E'}},
                {move: ['f', 'tr'], result: {x: 6, y: 17, direction: 'S'}},
                {move: ['f', 'tl'], result: {x: 7, y: 18, direction: 'E'}},
                {move: ['f', 'tr'], result: {x: 8, y: 18, direction: 'S'}},
                {move: ['f'], result: {x: 8, y: 19, direction: 'S'}},
                {move: ['f', 'tr', 'c', 'tr', 'tr'], result: {x: 8, y: 20, direction: 'E'}},
                {move: ['f', 'tr'], result: {x: 9, y: 20, direction: 'S'}},
                {move: ['f', 'tl', 'c', 'tl'], result: {x: 9, y: 21, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 9, y: 20, direction: 'W'}},
                {move: ['f', 'tr'], result: {x: 8, y: 20, direction: 'N'}},
                {move: ['f'], result: {x: 8, y: 19, direction: 'N'}},
                {move: ['f', 'tr'], result: {x: 8, y: 18, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 9, y: 18, direction: 'N'}},
                {move: ['f'], result: {x: 9, y: 17, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 9, y: 16, direction: 'W'}},
                {move: ['f', 'tr'], result: {x: 8, y: 16, direction: 'N'}},
                {move: ['f'], result: {x: 8, y: 15, direction: 'N'}},
                {move: ['f'], result: {x: 8, y: 14, direction: 'N'}},
                {move: ['f'], result: {x: 8, y: 13, direction: 'N'}},
                {move: ['f'], result: {x: 8, y: 12, direction: 'N'}},
                {move: ['f'], result: {x: 8, y: 11, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 8, y: 10, direction: 'W'}},
                {move: ['f'], result: {x: 7, y: 10, direction: 'W'}},
                {move: ['f', 'tr'], result: {x: 6, y: 10, direction: 'N'}},
                {move: ['f'], result: {x: 6, y: 9, direction: 'N'}},
                {move: ['f', 'tr'], result: {x: 6, y: 8, direction: 'E'}},
                {move: ['f'], result: {x: 7, y: 8, direction: 'E'}},
                {move: ['f', 'c', 'tr'], result: {x: 8, y: 8, direction: 'S'}},
                {move: ['f', 'tl'], result: {x: 8, y: 9, direction: 'E'}},
                {move: ['f'], result: {x: 9, y: 9, direction: 'E'}},
                {move: ['f', 'tr'], result: {x: 10, y: 9, direction: 'S'}},
                {move: ['f', 'c'], result: {x: 10, y: 10, direction: 'S'}},
                {move: ['b', 'tr'], result: {x: 10, y: 9, direction: 'W'}},
                {move: ['f'], result: {x: 9, y: 9, direction: 'W'}},
                {move: ['f', 'tr'], result: {x: 8, y: 9, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 8, y: 8, direction: 'W'}},
                {move: ['f'], result: {x: 7, y: 8, direction: 'W'}},
                {move: ['f'], result: {x: 6, y: 8, direction: 'W'}},
                {move: ['f'], result: {x: 5, y: 8, direction: 'W'}},
                {move: ['f', 'tl'], result: {x: 4, y: 8, direction: 'S'}},
                {move: ['f'], result: {x: 4, y: 9, direction: 'S'}},
                {move: ['f', 'tr'], result: {x: 4, y: 10, direction: 'W'}},
                {move: ['f'], result: {x: 3, y: 10, direction: 'W'}},
                {move: ['f', 'tl', 'c', 'c', 'tl'], result: {x: 2, y: 10, direction: 'E'}},
                {move: ['f'], result: {x: 3, y: 10, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 4, y: 10, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 9, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 4, y: 8, direction: 'W'}},
                {move: ['f'], result: {x: 3, y: 8, direction: 'W'}},
                {move: ['f', 'tl', 'tl'], result: {x: 2, y: 8, direction: 'E'}},
                {move: ['f'], result: {x: 3, y: 8, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 4, y: 8, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 7, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 6, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 5, direction: 'N'}},
                {move: ['f'], result: {x: 4, y: 4, direction: 'N'}},
                {move: ['f', 'tl', 'tl'], result: {x: 4, y: 3, direction: 'S'}},
                {move: ['f', 'tr'], result: {x: 4, y: 4, direction: 'W'}},
                {move: ['f'], result: {x: 3, y: 4, direction: 'W'}},
                {move: ['f', 'tl', 'tl'], result: {x: 2, y: 4, direction: 'E'}},
                {move: ['f'], result: {x: 3, y: 4, direction: 'E'}},
                {move: ['f', 'c', 'tr', 'c'], result: {x: 6, y: 4, direction: 'S'}},
                {move: ['f', 'tl', 'tl'], result: {x: 6, y: 5, direction: 'N'}},
                {move: ['f'], result: {x: 6, y: 4, direction: 'N'}},
                {move: ['f', 'tl', 'tl'], result: {x: 6, y: 3, direction: 'S'}},
                {move: ['f', 'tl', 'c'], result: {x: 7, y: 4, direction: 'E'}},
                {move: ['f'], result: {x: 8, y: 4, direction: 'E'}},
                {move: ['f', 'c', 'tl'], result: {x: 9, y: 4, direction: 'N'}},
                {move: ['f'], result: {x: 9, y: 3, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 9, y: 2, direction: 'W'}},
                {move: ['f'], result: {x: 8, y: 2, direction: 'W'}},
                {move: ['f'], result: {x: 7, y: 2, direction: 'W'}},
                {move: ['f', 'tr', 'c'], result: {x: 6, y: 2, direction: 'N'}}
            ]
        },
        v2: {
        }
    },
    2: {
        v1: {
            start: [1, 1],
            route: [
                {move: ['f'], result: {x: 1, y: 2, direction: 'S'}},
                {move: ['f'], result: {x: 1, y: 3, direction: 'S'}},
                {move: ['f', 'tl'], result: {x: 1, y: 4, direction: 'E'}},
                {move: ['f'], result: {x: 2, y: 4, direction: 'E'}},
                {move: ['f', 'tr'], result: {x: 3, y: 4, direction: 'S'}},
                {move: ['f', 'tr'], result: {x: 3, y: 5, direction: 'W'}},
                {move: ['f', 'tl'], result: {x: 2, y: 5, direction: 'S'}},
                {move: ['f'], result: {x: 2, y: 6, direction: 'S'}},
                {move: ['f', 'tr'], result: {x: 2, y: 7, direction: 'W'}},
                {move: ['f', 'tl'], result: {x: 1, y: 7, direction: 'S'}},
                {move: ['f'], result: {x: 1, y: 8, direction: 'S'}},
                {move: ['f', 'tl', 'tl'], result: {x: 1, y: 9, direction: 'N'}},
                {move: ['f'], result: {x: 1, y: 8, direction: 'N'}},
                {move: ['f', 'tr'], result: {x: 1, y: 7, direction: 'E'}},
                {move: ['f'], result: {x: 2, y: 7, direction: 'E'}},
                {move: ['f'], result: {x: 3, y: 7, direction: 'E'}},
                {move: ['f'], result: {x: 4, y: 7, direction: 'E'}},
                {move: ['f', 'tr'], result: {x: 5, y: 7, direction: 'S'}},
                {move: ['f'], result: {x: 5, y: 8, direction: 'S'}},
                {move: ['f', 'tl', 'tl'], result: {x: 5, y: 9, direction: 'N'}},
                {move: ['f'], result: {x: 5, y: 8, direction: 'N'}},
                {move: ['f', 'tr'], result: {x: 5, y: 7, direction: 'E'}},
                {move: ['f'], result: {x: 6, y: 7, direction: 'N'}},
                {move: ['f', 'tr'], result: {x: 7, y: 7, direction: 'S'}},
                {move: ['f'], result: {x: 7, y: 8, direction: 'S'}},
                {move: ['f', 'c', 'tl', 'tl'], result: {x: 7, y: 9, direction: 'N'}},
                {move: ['f'], result: {x: 7, y: 8, direction: 'N'}},
                {move: ['f', 'tr'], result: {x: 7, y: 7, direction: 'E'}},
                {move: ['f'], result: {x: 8, y: 7, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 9, y: 7, direction: 'N'}},
                {move: ['f', 'tr', 'c', 'tr'], result: {x: 9, y: 6, direction: 'S'}},
                {move: ['f'], result: {x: 9, y: 7, direction: 'S'}},
                {move: ['f'], result: {x: 9, y: 8, direction: 'S'}},
                {move: ['f', 'tl', 'tl'], result: {x: 9, y: 9, direction: 'N'}},
                {move: ['f'], result: {x: 9, y: 8, direction: 'N'}},
                {move: ['f', 'tl'], result: {x: 9, y: 7, direction: 'W'}},
                {move: ['f'], result: {x: 8, y: 7, direction: 'W'}},
                {move: ['f'], result: {x: 7, y: 7, direction: 'W'}},
                {move: ['f'], result: {x: 6, y: 7, direction: 'W'}},
                {move: ['f', 'tr'], result: {x: 5, y: 7, direction: 'N'}},
                {move: ['f'], result: {x: 5, y: 6, direction: 'N'}},
                {move: ['f'], result: {x: 5, y: 5, direction: 'N'}},
                {move: ['f'], result: {x: 5, y: 4, direction: 'N'}},
                {move: ['f'], result: {x: 5, y: 3, direction: 'N'}},
                {move: ['f', 'tl', 'tl'], result: {x: 5, y: 2, direction: 'S'}},
                {move: ['f'], result: {x: 5, y: 3, direction: 'S'}},
                {move: ['f', 'tl'], result: {x: 5, y: 4, direction: 'E'}},
                {move: ['f'], result: {x: 6, y: 4, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 7, y: 4, direction: 'N'}},
                {move: ['f'], result: {x: 7, y: 3, direction: 'N'}},
                {move: ['f', 'tl', 'tl'], result: {x: 7, y: 2, direction: 'S'}},
                {move: ['f'], result: {x: 7, y: 3, direction: 'S'}},
                {move: ['f', 'tl'], result: {x: 7, y: 4, direction: 'E'}},
                {move: ['f'], result: {x: 8, y: 4, direction: 'E'}},
                {move: ['f', 'tl'], result: {x: 9, y: 4, direction: 'N'}},
                {move: ['f'], result: {x: 9, y: 3, direction: 'N'}},
                {move: ['f'], result: {x: 9, y: 2, direction: 'N'}},
                {move: ['f'], result: {x: 9, y: 1, direction: 'N'}},
            ]
        },
        v2: {
            start: [13, 10],
            route: [
            ]
        }
    },
    3: {
        v1: {
            start: [1, 1],
            route: [
            ]
        },
        v2: {
        }
    }
};